name: Manual operation

on:
  workflow_dispatch:
    inputs:
      flutter_channel:
        default: 'stable'
        required: true
        type: choice
        options:
          - beta
          - master
          - stable

jobs:
  # 编译Windows
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ inputs.flutter_channel }}
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor

      - name: Checking flutter
        run: flutter doctor --verbose

      - name: Analyze project source
        run: dart analyze

      - name: Build ZIP
        run: flutter_distributor package --platform windows --targets zip

      - name: Archive ZIP
        uses: actions/upload-artifact@v4
        with:
          name: market_upload_windows
          path: |
            dist/**
          overwrite: true
          compression-level: 9
          retention-days: 2
  # 编译MacOS
  build-macos:
    name: Build MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ inputs.flutter_channel }}
          cache: true

      - name: Install Dependencies
        run: flutter pub get
        shell: bash

      - name: Checking flutter
        run: flutter doctor --verbose
        shell: bash

      - name: Analyze project source
        run: dart analyze
        shell: bash

      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor
        shell: bash

      # 安装nodejs
      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install appdmg
        run: npm install -g appdmg
        shell: bash

      - name: Build DMG
        run: flutter_distributor package --platform macos --targets dmg
        shell: bash

      - name: Archive DMG
        uses: actions/upload-artifact@v4
        with:
          name: market_upload_macos
          path: |
            dist/**
          overwrite: true
          compression-level: 9
          retention-days: 2

  release:
    name: Release
    needs: [ build-windows, build-macos ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      # 下载各平台的编译文件
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          github-token: ${{ secrets.MARKET_UPLOAD }}
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            artifacts/**
          draft: true
          token: ${{ secrets.MARKET_UPLOAD }}
