name: Build and publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get
        shell: bash

      - name: Checking flutter
        run: flutter doctor --verbose
        shell: bash

      - name: Analyze project source
        run: dart analyze
        shell: bash

      - name: Build EXE
        run: flutter build windows -v
        shell: bash

      - name: ZIP EXE
        uses: edgarrc/action-7z@v1
        with:
          args: 7z a -t7z -mx=9 market_upload_windows.7z ./build/windows/x64/runner/Release/

      - name: Release EXE
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            market_upload_windows.7z
          draft: true
          token: ${{ secrets.MARKET_UPLOAD }}

      - name: Archive EXE
        uses: actions/upload-artifact@v4
        with:
          name: market_upload_windows
          path: |
            build/windows/x64/runner/Release/**
          overwrite: true
          compression-level: 9
          retention-days: 2
